name: CI/CD Pipeline for 3. Integration Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Compose
      uses: docker/setup-qemu-action@v2

    - name: Ensure Docker Compose is available
      run: docker-compose version

    - name: Copy .env.example to .env
      run: cp ./3. Integration and E2E Testing/1. Integration Testing/.env.example ./3. Integration and E2E Testing/1. Integration Testing/.env

    - name: Run integration script
      run: cd 3. Integration and E2E Testing/1. Integration Testing && npm run test:integration
